"""empty message

Revision ID: 5480ad5bd09d
Revises: c4a20dac551f
Create Date: 2021-11-24 14:15:58.069008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5480ad5bd09d'
down_revision = 'c4a20dac551f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_product_id_fkey', 'cart', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('cart_product_id_fkey', 'cart', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
