"""empty message

Revision ID: feaebe30d294
Revises: 5480ad5bd09d
Create Date: 2021-11-24 14:17:17.162138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feaebe30d294'
down_revision = '5480ad5bd09d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_key', sa.String(), nullable=True))
    op.drop_column('cart', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('cart', 'product_key')
    # ### end Alembic commands ###
